# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import message_pb2 as message__pb2


class NodeCommStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Func_Exec = channel.unary_unary(
                '/FunctionComposotion.NodeComm/Func_Exec',
                request_serializer=message__pb2.RequestInfo.SerializeToString,
                response_deserializer=message__pb2.ReplyInfo.FromString,
                )


class NodeCommServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Func_Exec(self, request, context):
        """rpc FC_NodeComm(RequestInfo) returns (ReplyInfo) {}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeCommServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Func_Exec': grpc.unary_unary_rpc_method_handler(
                    servicer.Func_Exec,
                    request_deserializer=message__pb2.RequestInfo.FromString,
                    response_serializer=message__pb2.ReplyInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FunctionComposotion.NodeComm', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NodeComm(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Func_Exec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FunctionComposotion.NodeComm/Func_Exec',
            message__pb2.RequestInfo.SerializeToString,
            message__pb2.ReplyInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
